import React from 'react';
import { motion } from 'motion/react';
import { FileText, Shield, Gavel, Scale, AlertTriangle, CheckCircle2 } from 'lucide-react';

export default function Terms() {
  const sections = [
    {
      title: "Acceptance of Terms",
      icon: CheckCircle2,
      content: "By accessing or using ResumeMorph, you agree to be bound by these Terms of Service. If you do not agree, you may not use our services."
    },
    {
      title: "User Accounts",
      icon: Shield,
      content: "You are responsible for maintaining the confidentiality of your account credentials. All activities under your account are your responsibility."
    },
    {
      title: "Intellectual Property",
      icon: Gavel,
      content: "All content generated by ResumeMorph, excluding your personal data, is the property of ResumeMorph Inc. and protected by copyright laws."
    },
    {
      title: "Limitation of Liability",
      icon: Scale,
      content: "ResumeMorph provides tools for career advancement but does not guarantee employment results. We are not liable for any indirect or consequential damages."
    }
  ];

  return (
    <div className="min-h-screen bg-[var(--bg-primary)] py-20 px-4">
      <div className="max-w-4xl mx-auto">
        <motion.div 
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          className="text-center mb-20"
        >
          <div className="w-20 h-20 bg-indigo-50 dark:bg-indigo-900/20 rounded-[24px] flex items-center justify-center mx-auto mb-8">
            <FileText className="w-10 h-10 text-indigo-600" />
          </div>
          <h1 className="text-4xl md:text-6xl font-black text-[var(--text-primary)] mb-6 tracking-tight">
            Terms & <span className="saas-gradient-text">Conditions</span>
          </h1>
          <p className="text-[10px] font-black uppercase tracking-[0.3em] text-[var(--text-tertiary)] mb-4">
            Last Updated: June 27, 2026
          </p>
          <p className="text-lg text-[var(--text-secondary)] font-medium leading-relaxed">
            Please read these terms carefully before using our platform. They govern your relationship with ResumeMorph.
          </p>
        </motion.div>

        <div className="space-y-12 mb-20">
          {sections.map((section, i) => (
            <motion.div 
              key={i}
              initial={{ opacity: 0, x: -20 }}
              animate={{ opacity: 1, x: 0 }}
              transition={{ delay: i * 0.1 }}
              className="group flex gap-8 p-8 bg-[var(--bg-secondary)] border border-[var(--border-color)] rounded-[32px] hover:border-indigo-400 transition-all"
            >
              <div className="w-14 h-14 bg-[var(--bg-primary)] rounded-2xl flex items-center justify-center shrink-0 border border-[var(--border-color)] group-hover:scale-110 transition-transform">
                <section.icon className="w-6 h-6 text-indigo-600" />
              </div>
              <div>
                <h3 className="text-xl font-black text-[var(--text-primary)] mb-4">{section.title}</h3>
                <p className="text-[var(--text-secondary)] font-medium leading-relaxed">
                  {section.content}
                </p>
              </div>
            </motion.div>
          ))}
        </div>

        <div className="bg-amber-50 dark:bg-amber-950/20 border border-amber-100 dark:border-amber-900/50 rounded-[32px] p-8 mb-20">
          <div className="flex gap-6">
            <AlertTriangle className="w-8 h-8 text-amber-600 shrink-0" />
            <div>
              <h4 className="text-xl font-black text-amber-900 dark:text-amber-400 mb-2">Important Notice</h4>
              <p className="text-amber-800 dark:text-amber-500 font-medium leading-relaxed">
                We reserve the right to modify these terms at any time. Significant changes will be notified via email or a prominent notice on our website.
              </p>
            </div>
          </div>
        </div>

        <div className="prose prose-slate dark:prose-invert max-w-none space-y-8 text-[var(--text-secondary)] font-medium">
          <h2 className="text-2xl font-black text-[var(--text-primary)]">Detailed Usage Policies</h2>
          <p>
            You agree not to use the service for any illegal or unauthorized purpose. You must not, in the use of the Service, violate any laws in your jurisdiction.
          </p>
          <p>
            We may, but have no obligation to, remove Content and Accounts containing Content that we determine in our sole discretion are unlawful, offensive, threatening, libelous, defamatory, pornographic, obscene or otherwise objectionable or violates any party’s intellectual property or these Terms of Service.
          </p>
          <p>
            Questions about the Terms of Service should be sent to <span className="text-indigo-600 font-bold">legal@resumemorph.com</span>.
          </p>
        </div>

        <div className="mt-20 pt-12 border-t border-[var(--border-color)] text-center">
          <p className="text-[var(--text-tertiary)] font-bold text-sm">
            © 2026 ResumeMorph Inc. All Rights Reserved.
          </p>
        </div>
      </div>
    </div>
  );
}
